"""changes models

Revision ID: 0669fdc64711
Revises: 90c667b8f47e
Create Date: 2024-11-16 11:29:59.670704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0669fdc64711'
down_revision = '90c667b8f47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('food_allergies', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activity_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], name=op.f('fk_activity_record_pet_id_pet')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], name=op.f('fk_appointment_pet_id_pet')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('veterinary', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], name=op.f('fk_health_record_pet_id_pet')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_pet',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], name=op.f('fk_user_pet_pet_id_pet')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_pet_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'pet_id')
    )
    op.create_table('vaccination',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('next_due', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], name=op.f('fk_vaccination_pet_id_pet')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weight_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=5), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], name=op.f('fk_weight_record_pet_id_pet')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_record')
    op.drop_table('vaccination')
    op.drop_table('user_pet')
    op.drop_table('health_record')
    op.drop_table('appointment')
    op.drop_table('activity_record')
    op.drop_table('user')
    op.drop_table('pet')
    # ### end Alembic commands ###
