"""Add user_id to Appointment table

Revision ID: 2e2c9e53554c
Revises: 4515fcc9d9d8
Create Date: 2024-11-18 21:33:50.843847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2c9e53554c'
down_revision = '4515fcc9d9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'appointment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'user_id')
    # ### end Alembic commands ###
