"""removes user_id to Vaccination table

Revision ID: fd6673800949
Revises: 8f12489f397e
Create Date: 2024-11-18 22:17:54.818123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6673800949'
down_revision = '8f12489f397e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'appointment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    # ### end Alembic commands ###
